[build]
command = "cd backend && ./mvnw -DskipTests clean package -Dspring-boot.repackage=true"
outputDirectory = "backend/target"

[deploy]
startCommand = "java -jar backend/target/demo11111-0.0.1-SNAPSHOT.jar --server.port=${PORT} --server.address=0.0.0.0"

[variables]
PORT = "8080"

[healthcheck]
path = "/actuator/health"
timeout = 120
interval = 5s