[build]
command = "cd backend && ./mvnw -DskipTests clean package -Dspring-boot.repackage=true"
outputDirectory = "backend/target"

[deploy]
startCommand = "java -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar backend/target/demo11111-0.0.1-SNAPSHOT.jar"

[variables]
PORT = "8080"