[build]
# Билдим оба проекта
command = """
  cd backend && ./mvnw -DskipTests clean package && \
  cd ../frontend && npm install && npm run build
"""
outputDirectory = "backend/target"  # Где лежит бэкенд JAR

[deploy]
# Сначала запускаем бэкенд, потом фронт через nginx
startCommand = """
  java -Dserver.port=$PORT -jar backend/target/demo11111-*.jar & \
  serve -s frontend/build -l $FRONTEND_PORT
"""

[variables]
PORT = "8080"              # Порт для бэкенда
FRONTEND_PORT = "3000"     # Порт для фронтенда
DATABASE_URL = "${PostgreSQL.DATABASE_URL}"  # Для БД

# Health-чеки
[[healthchecks]]
name = "backend"
interval = 10
timeout = 5
path = "/health"

[[healthchecks]]
name = "frontend"
interval = 15
timeout = 5
path = "/"