[build]
command = """
  cd backend && ./mvnw -DskipTests clean package && \
  cd ../frontend && npm install && npm run build
"""
outputDirectory = "backend/target"

[deploy]
startCommand = """
  (java -Dserver.port=$PORT -jar backend/target/demo11111-*.jar) & \
  (cd frontend && npx serve -s build -l $FRONTEND_PORT)
"""

[variables]
PORT = "8080"
FRONTEND_PORT = "3000"